#!/bin/sh

SCRIPT_DIR=`dirname $0`
SCRAPE_SCRIPT="$SCRIPT_DIR/twitter_scrape"

FOLLOWER_HISTORY_DIR="follow_history"
FOLLOWER_HISTORY_FILE="$FOLLOWER_HISTORY_DIR/follwers.txt"

ERROR_FILE="errors.txt"

$SCRAPE_SCRIPT >$FOLLOWER_HISTORY_FILE 2>$ERROR_FILE

GIT_BIN="git"
GIT_CMD="$GIT_BIN --git-dir=$FOLLOWER_HISTORY_DIR/.git --work-tree=$FOLLOWER_HISTORY_DIR"

$GIT_CMD commit -a -m 'auto-checkin of follower history' >/dev/null 2>>$ERROR_FILE
$GIT_CMD push github master:master >/dev/null 2>>$ERROR_FILE

