#!/bin/bash

BASE_DIR=`dirname $0`
HISTORY_DIR="${BASE_DIR}/../twitter_follower_history_data"

# Followers
echo "followers"
FOLLOWERS_CMD="twitter-follow -o -i dragonfax"
FOLLOWER_HISTORY_FILE="${HISTORY_DIR}/follwers.txt"
$FOLLOWERS_CMD | /usr/bin/sort -n >"${FOLLOWER_HISTORY_FILE}"


# Following
echo "following"
FOLLOWING_CMD="twitter-follow -o -i -g dragonfax"
FOLLOWING_HISTORY_FILE="${HISTORY_DIR}/following.txt"
$FOLLOWING_CMD | /usr/bin/sort -n >"${FOLLOWING_HISTORY_FILE}"


# Git Tracking
echo "commiting new file version"
GIT_CMD="git --git-dir=${HISTORY_DIR}/.git --work-tree=${HISTORY_DIR}"
$GIT_CMD commit -a -m 'auto-checkin of follower history'

echo "pushing to github"
$GIT_CMD push

