#!/usr/bin/env python

import twitter
import twitter_api_credentials

if not twitter.__version__ >= 0.8:
	raise Exception("twitter api wrong version");

api = twitter.Api( 
					consumer_key = twitter_api_credentials.CONSUMER_KEY , 
					consumer_secret = twitter_api_credentials.CONSUMER_SECRET, 
					access_token_key = twitter_api_credentials.ACCESS_TOKEN_KEY, 
					access_token_secret = twitter_api_credentials.ACCESS_TOKEN_SECRET)

# print api.VerifyCredentials()


# pull all following users
cursor = -1
following_users = []
while cursor != 0:
	# print "pulling for cursor %d" % cursor
	ret = api.GetFollowers(cursor=cursor)
	following_users += ret["users"]
	cursor = ret["next_cursor"]

# following_users = api.GetFollowers()

# print "finished pulling"

# output handles
def map_handle(user): 
	return user.screen_name

following_handles = map(map_handle,  following_users)

for handle in sorted(following_handles):
	print handle

